### ISSUE TITLE
Bug on thumbnail view

### ISSUE THREAD

**Issue by kyzsuukii** [AP-Atul/music_player_lite#11]
![Screenshot_2022-08-24-00-56-00-752_com.atul.musicplayeronline.jpg](https://user-images.githubusercontent.com/110718021/186218583-abd6dcb7-cf5c-486e-9be3-97db7ca4492e.jpg)

thumbnail photos all look the same and use one thumbnail of one song in all songs

even though in my file manager everything is different

![Screenshot_2022-08-24-00-56-18-285_me.zhanghai.android.files.jpg](https://user-images.githubusercontent.com/110718021/186219231-bf854d77-066a-4a79-b0f1-43200d49fc96.jpg)

**Comment by AP-Atul** [comment]
Thanks for reporting the issue, will surely get around to fixing this soon. Stay tuned

**Comment by AP-Atul** [comment]
BTW, The Album art is fetched based on the Album Id or can say based on Album. What happens is that when the Song has no album data embedded they get assigned to the default folder name. 

So now all the songs with no album data are in the same Album. In my app, I have a folder `Music` which is shown as the album with 74 songs and all songs have same album art.
The fix will not show a default album art instead of a same for all. Will look for a way to extract from the music file itself.

I have updated the code to fix this issue [here](https://github.com/AP-Atul/music_player_lite/commit/3dcef33ceb0c71a5dec2f3751ebe7fa8398b7966)

The changes will be available in next release, which should be soon or you can build it youself ;)
